import type { Metadata } from "next";
import { PT_Sans } from "next/font/google";
import "./globals.css";
import SiteHeader from '@/components/SiteHeader/SiteHeader';
import SiteFooter from '@/components/SiteFooter/SiteFooter';

const ptSans = PT_Sans({
  subsets: ['latin'],
  weight: ['400', '700'], // PT Sans comes in regular and bold
  variable: '--font-pt-sans', // This creates a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ptSans.variable} ${ptSans.className} antialiased`}
      >
        <SiteHeader></SiteHeader>
        {children}
        <SiteFooter></SiteFooter>
      </body>
    </html>
  );
}
